version: 2
jobs:
  buildDev:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - restore_cache:
          keys:
            - dependency-cache
            - install4j-cache
      - checkout
      - run: scripts/prepare-install4j.sh
      # update locally with:
      # openssl aes-256-cbc -e -in ./buildres/jabref-cert-2016.p12 -out jabref-cert-2016.p12.enc -k {PASSWORD}
      - run: install4j6/bin/install4jc --verbose --license=$INSTALL4J_KEY --win-keystore-password $CERTIFICATE_PW --mac-keystore-password $CERTIFICATE_PW
      - run: openssl aes-256-cbc -d -in ./buildres/jabref-cert-2016.p12.enc -out ./buildres/jabref-cert-2016.p12 -k $CERTIFICATE
      - run: ./gradlew -Pdev=true -Pinstall4jDir="install4j6" release --stacktrace
      - save_cache:
          key: dependency-cache
          paths:
            - "~/.gradle"
      - save_cache:
          key: install4j-cache
          paths:
            - "~/downloads"
            - "~/.install4j6"
      - store_artifacts:
          path: build/releases
          destination: build
    deploy:
      command: scripts/upload-to-builds.jabref.org.sh

  buildRelease:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - restore_cache:
          keys:
            - dependency-cache
            - install4j-cache
      - checkout
      - run: |
        set -eu
        TAG=$(git describe --tags)
        if [[ $TAG =~ ^[0-9]+(\.[0-9]+)+(-rc[0-9]+)?(-alpha[0-9]+)?$ ]]; then
          openssl aes-256-cbc -d -in ./buildres/jabref-cert-2016.p12.enc -out ./buildres/jabref-cert-2016.p12 -k $CERTIFICATE
          install4j6/bin/install4jc --verbose --license=$INSTALL4J_KEY --win-keystore-password $CERTIFICATE_PW --mac-keystore-password $CERTIFICATE_PW
          ./gradlew -Pinstall4jDir="install4j6" clean release --stacktrace
        fi
    deploy:
      command: scripts/upload-to-builds.jabref.org.sh

workflows:
  version: 2

  build:
    jobs:
      - buildDev:
          requires:
            - prepareInstall4J
      - buildRelease:
          requires:
            - buildDev
          filters:
            branches:
              only: "circleci20"
